### ISSUE TITLE
请教 macOS 系统中如何使用

### ISSUE THREAD

**Issue by flyinguard** [JACKCHAN000/Rime-Lua-GoogleTranslate#2]
你好，项目非常好，我在我Windows系统中已经使用了很长一段时间，运行丝滑，非常感谢。
但是我最近切换到macos系统，在rime中无法成功设置rime-lua-googleTranslate，自己编程语言小白，尽管在此鼓捣了很久，仍无法配置成功，特向您请教，如何设置这一项目的环境。
先行致谢。
-----
今天无意中调试好了，是lua运行环境的问题。不过还是感谢该项目和ctermiii的帮助。

**Comment by ctermiii** [comment]
参考librime-cloud项目
